#!/bin/bash

# Quick testing guide for email and PDF features
# This script helps verify the implementation is working

set -e

echo "==========================================="
echo "Email & PDF Export Feature Testing Guide"
echo "==========================================="
echo ""

echo "STEP 1: Check environment variables"
echo "===================================="
echo ""
echo "Required variables for local testing:"
echo "  EMAIL_PROVIDER=mock"
echo "  EMAIL_FROM=noreply@localhost.local"
echo "  EMAIL_FROM_NAME=Pavilion"
echo "  EMAIL_REPLY_DOMAIN=localhost.local"
echo "  APP_BASE_URL=http://localhost:5173"
echo ""
echo "Run:"
echo "  cat > .env.local << EOF"
echo "EMAIL_PROVIDER=mock"
echo "EMAIL_FROM=noreply@localhost.local"
echo "EMAIL_FROM_NAME=Pavilion"
echo "EMAIL_REPLY_DOMAIN=localhost.local"
echo "APP_BASE_URL=http://localhost:5173"
echo "EOF"
echo ""

echo "STEP 2: Install dependencies"
echo "=============================="
echo ""
echo "The implementation needs pdfkit for PDF generation:"
echo ""
echo "  npm install pdfkit @types/pdfkit"
echo ""

echo "STEP 3: Start Convex development server"
echo "========================================="
echo ""
echo "  npm run convex:dev"
echo ""

echo "STEP 4: Test Email Notifications (Mock Provider)"
echo "=================================================="
echo ""
echo "1. Open the app at http://localhost:5173"
echo "2. Go to the chat/messaging page"
echo "3. Send a message in a conversation"
echo "4. Look at the Convex dev server logs"
echo ""
echo "Expected output in logs:"
echo '  [EMAIL] Mock send (mock_1234567890_abc123...):'
echo '  { to: [...], from: {...}, subject: \"New message...\", ... }'
echo ""
echo "The email is logged but not actually sent (mock provider)."
echo ""

echo "STEP 5: Test with SendGrid (Optional)"
echo "======================================"
echo ""
echo "To test with a real provider:"
echo ""
echo "1. Get API key from https://app.sendgrid.com/settings/api_keys"
echo "2. Set environment:"
echo "   export SENDGRID_API_KEY='SG.your_key_here'"
echo "   export EMAIL_PROVIDER=sendgrid"
echo "3. Restart dev server"
echo "4. Send a message"
echo "5. Check SendGrid dashboard for sent email"
echo ""

echo "STEP 6: Test Inbound Email Webhook"
echo "==================================="
echo ""
echo "Local testing requires publicly accessible URL:"
echo ""
echo "1. Install ngrok: brew install ngrok (macOS)"
echo "2. Run: ngrok http 3000"
echo "3. Get public URL (e.g., https://abc-123-456.ngrok.io)"
echo "4. Configure in email provider:"
echo "   - Webhook URL: https://abc-123-456.ngrok.io/api/email/inbound"
echo "5. Reply to an email"
echo "6. Check server logs for webhook receipt"
echo ""
echo "Note: Webhook implementation is incomplete (see TODO comments)"
echo ""

echo "STEP 7: Test PDF Export"
echo "======================="
echo ""
echo "1. Make sure messages exist in conversation"
echo "2. Click \"📄 Export as PDF\" button"
echo "3. Browser should download PDF file"
echo "4. Open PDF and verify content"
echo ""
echo "Note: PDF export endpoint is not fully implemented (see TODO)"
echo ""

echo "DEBUGGING"
echo "=========="
echo ""
echo "Check logs:"
echo "  grep '\\[EMAIL\\]' $(npm run convex:dev 2>&1)"
echo ""
echo "Check TypeScript compilation:"
echo "  npm run build"
echo ""
echo "Reset database:"
echo "  npx convex wipe"
echo "  npx convex run seed:seedDemoData"
echo ""

echo "PROVIDER-SPECIFIC SETUP"
echo "======================="
echo ""
echo "SendGrid:"
echo "  1. Create account at https://sendgrid.com"
echo "  2. Create API key (Settings > API Keys)"
echo "  3. Verify domain (Settings > Sender Verification)"
echo "  4. Enable Inbound Parse (Settings > Inbound Parse)"
echo "  5. Add domain and webhook URL"
echo ""
echo "Mailgun:"
echo "  1. Create account at https://mailgun.com"
echo "  2. Create API key"
echo "  3. Verify domain"
echo "  4. Set up receiving route"
echo ""
echo "Postmark:"
echo "  1. Create account at https://postmarkapp.com"
echo "  2. Create server and API key"
echo "  3. Enable inbound in server settings"
echo "  4. Set webhook URL"
echo ""

echo "==========================================="
echo "Implementation Status"
echo "==========================================="
echo ""
echo "✅ Completed:"
echo "  - Email schema and types"
echo "  - Email provider abstraction"
echo "  - Email templates (HTML and text)"
echo "  - Notification trigger in sendMessage"
echo "  - PDF generator template"
echo "  - Export button UI"
echo "  - Thread ID generation/extraction"
echo ""
echo "🚧 TODO:"
echo "  - Complete email provider API implementations"
echo "  - Implement HTTP handler for PDF export"
echo "  - Implement HTTP handler for inbound emails"
echo "  - User lookup and creation for email senders"
echo "  - Webhook signature verification"
echo "  - Duplicate detection for emails"
echo "  - Access control and rate limiting"
echo ""

echo "See IMPLEMENTATION_GUIDE.md for detailed instructions."
echo ""
