import type { Doc } from "../_generated/dataModel";

/** Demo rows for the `people` table (directory / contacts). */
export const DEMO_PEOPLE: Omit<Doc<"people">, "_id" | "_creationTime">[] = [
  {
    name: "Larry Mar",
    email: "larry.mar@imperialdade.com",
    phone: "(408) 555-0192",
    website: "https://imperialdade.com",
    role: "Government Sales Representative",
    bio: "Larry specializes in janitorial and sanitation supplies for municipal and state facilities.",
    location: "San Jose, CA",
    avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    company: "Imperial Bag & Paper Co LLC",
    companyName: "Imperial Bag & Paper Co LLC",
    companyDescription: "A leading national distributor of janitorial, sanitation, and foodservice supplies.",
    responseTime: "Usually responds within 2 hours",
    preferences: ["Email", "Phone"],
  },
  {
    name: "Sarah Chen",
    email: "sarah.chen@govtechsolutions.com",
    phone: "(415) 555-0147",
    website: "https://govtechsolutions.com",
    role: "Public Sector Account Manager",
    bio: "Sarah manages IT infrastructure and software procurement contracts for local governments.",
    location: "San Francisco, CA",
    avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    company: "GovTech Solutions Inc.",
    companyName: "GovTech Solutions Inc.",
    companyDescription: "Providing modern IT infrastructure and cloud software solutions for local governments.",
    responseTime: "Usually responds within 1 hour",
    preferences: ["Email"],
  },
  {
    name: "Marcus Johnson",
    email: "mjohnson@buildrightcorp.com",
    phone: "(916) 555-0183",
    website: "https://buildrightcorp.com",
    role: "Director of Public Works Bidding",
    bio: "Marcus oversees construction and public works bidding, specializing in infrastructure projects.",
    location: "Sacramento, CA",
    avatarUrl: "https://randomuser.me/api/portraits/men/67.jpg",
    company: "BuildRight Construction Corp.",
    companyName: "BuildRight Construction Corp.",
    companyDescription: "Specializing in large-scale public works and infrastructure construction projects.",
    responseTime: "Usually responds within 24 hours",
    preferences: ["Phone"],
  },
  {
    name: "Priya Patel",
    email: "ppatel@medsupplygov.com",
    phone: "(213) 555-0261",
    website: "https://medsupplygov.com",
    role: "State Contracts Specialist",
    bio: "Priya focuses on fulfilling medical and emergency supply contracts for state health departments.",
    location: "Los Angeles, CA",
    avatarUrl: "https://randomuser.me/api/portraits/women/68.jpg",
    company: "MedSupply Government Division",
    companyName: "MedSupply Government Division",
    companyDescription: "Supplying state health departments with critical medical and emergency equipment.",
    responseTime: "Usually responds within 4 hours",
    preferences: ["Email", "Text"],
  },
  {
    name: "David Kim",
    email: "dkim@govtechsolutions.com",
    phone: "(415) 555-0199",
    website: "https://govtechsolutions.com",
    role: "Cloud Solutions Architect",
    bio: "David designs secure cloud environments for state agencies and municipalities.",
    location: "San Francisco, CA",
    avatarUrl: "https://randomuser.me/api/portraits/men/22.jpg",
    company: "GovTech Solutions Inc.",
    companyName: "GovTech Solutions Inc.",
    companyDescription: "Providing modern IT infrastructure and cloud software solutions for local governments.",
    responseTime: "Usually responds within 2 hours",
    preferences: ["Email", "Phone"],
  },
  {
    name: "Elena Rodriguez",
    email: "erodriguez@buildrightcorp.com",
    phone: "(916) 555-0210",
    website: "https://buildrightcorp.com",
    role: "Senior Estimator",
    bio: "Elena specializes in cost estimation and bidding for municipal infrastructure projects.",
    location: "Sacramento, CA",
    avatarUrl: "https://randomuser.me/api/portraits/women/33.jpg",
    company: "BuildRight Construction Corp.",
    companyName: "BuildRight Construction Corp.",
    companyDescription: "Specializing in large-scale public works and infrastructure construction projects.",
    responseTime: "Usually responds within 24 hours",
    preferences: ["Email"],
  },
  {
    name: "Michael Chang",
    email: "mchang@medsupplygov.com",
    phone: "(213) 555-0344",
    website: "https://medsupplygov.com",
    role: "Logistics Coordinator",
    bio: "Michael ensures timely delivery of emergency medical supplies to county hospitals.",
    location: "Los Angeles, CA",
    avatarUrl: "https://randomuser.me/api/portraits/men/44.jpg",
    company: "MedSupply Government Division",
    companyName: "MedSupply Government Division",
    companyDescription: "Supplying state health departments with critical medical and emergency equipment.",
    responseTime: "Usually responds within 4 hours",
    preferences: ["Phone", "Text"],
  },
  {
    name: "Rachel Foster",
    email: "rfoster@govtechsolutions.com",
    phone: "(415) 555-0188",
    website: "https://govtechsolutions.com",
    role: "Cybersecurity Consultant",
    bio: "Rachel helps local governments implement zero-trust security architectures and compliance.",
    location: "San Francisco, CA",
    avatarUrl: "https://randomuser.me/api/portraits/women/55.jpg",
    company: "GovTech Solutions Inc.",
    companyName: "GovTech Solutions Inc.",
    companyDescription: "Providing modern IT infrastructure and cloud software solutions for local governments.",
    responseTime: "Usually responds within 1 hour",
    preferences: ["Email"],
  },
];
